// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/users/userinfo_messages.proto

package users

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_api_users_userinfo_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_userinfo_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_api_users_userinfo_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserInfoUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoUpdateRequest) Reset() {
	*x = UserInfoUpdateRequest{}
	mi := &file_api_users_userinfo_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoUpdateRequest) ProtoMessage() {}

func (x *UserInfoUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_userinfo_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserInfoUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_users_userinfo_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfoUpdateRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfoUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoUpdateRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfoUpdateRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UserInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthSystem     string                 `protobuf:"bytes,2,opt,name=auth_system,json=authSystem,proto3" json:"auth_system,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GivenName      string                 `protobuf:"bytes,4,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName     string                 `protobuf:"bytes,5,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Avatar         string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email          string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Role           string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	GuideCompleted bool                   `protobuf:"varint,9,opt,name=guide_completed,json=guideCompleted,proto3" json:"guide_completed,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	VerifiedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	LastLoginIp    string                 `protobuf:"bytes,12,opt,name=last_login_ip,json=lastLoginIp,proto3" json:"last_login_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_users_userinfo_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_userinfo_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_users_userinfo_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetAuthSystem() string {
	if x != nil {
		return x.AuthSystem
	}
	return ""
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *UserInfo) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetGuideCompleted() bool {
	if x != nil {
		return x.GuideCompleted
	}
	return false
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *UserInfo) GetLastLoginIp() string {
	if x != nil {
		return x.LastLoginIp
	}
	return ""
}

var File_api_users_userinfo_messages_proto protoreflect.FileDescriptor

const file_api_users_userinfo_messages_proto_rawDesc = "" +
	"\n" +
	"!api/users/userinfo_messages.proto\x12\tapi.users\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x02id\"o\n" +
	"\x15UserInfoUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\"\x96\x03\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vauth_system\x18\x02 \x01(\tR\n" +
	"authSystem\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"given_name\x18\x04 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x05 \x01(\tR\n" +
	"familyName\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\x12'\n" +
	"\x0fguide_completed\x18\t \x01(\bR\x0eguideCompleted\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vverified_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12\"\n" +
	"\rlast_login_ip\x18\f \x01(\tR\vlastLoginIpB\xa3\x01\n" +
	"\rcom.api.usersB\x15UserinfoMessagesProtoP\x01Z6smart-analytics/assistants/grpc/protobuf/pkg/api/users\xa2\x02\x03AUX\xaa\x02\tApi.Users\xca\x02\tApi\\Users\xe2\x02\x15Api\\Users\\GPBMetadata\xea\x02\n" +
	"Api::Usersb\x06proto3"

var (
	file_api_users_userinfo_messages_proto_rawDescOnce sync.Once
	file_api_users_userinfo_messages_proto_rawDescData []byte
)

func file_api_users_userinfo_messages_proto_rawDescGZIP() []byte {
	file_api_users_userinfo_messages_proto_rawDescOnce.Do(func() {
		file_api_users_userinfo_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_userinfo_messages_proto_rawDesc), len(file_api_users_userinfo_messages_proto_rawDesc)))
	})
	return file_api_users_userinfo_messages_proto_rawDescData
}

var file_api_users_userinfo_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_users_userinfo_messages_proto_goTypes = []any{
	(*UserRequest)(nil),           // 0: api.users.UserRequest
	(*UserInfoUpdateRequest)(nil), // 1: api.users.UserInfoUpdateRequest
	(*UserInfo)(nil),              // 2: api.users.UserInfo
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_users_userinfo_messages_proto_depIdxs = []int32{
	3, // 0: api.users.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: api.users.UserInfo.verified_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_users_userinfo_messages_proto_init() }
func file_api_users_userinfo_messages_proto_init() {
	if File_api_users_userinfo_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_userinfo_messages_proto_rawDesc), len(file_api_users_userinfo_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_users_userinfo_messages_proto_goTypes,
		DependencyIndexes: file_api_users_userinfo_messages_proto_depIdxs,
		MessageInfos:      file_api_users_userinfo_messages_proto_msgTypes,
	}.Build()
	File_api_users_userinfo_messages_proto = out.File
	file_api_users_userinfo_messages_proto_goTypes = nil
	file_api_users_userinfo_messages_proto_depIdxs = nil
}
