// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/users/userinfo.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_users_userinfo_proto protoreflect.FileDescriptor

const file_api_users_userinfo_proto_rawDesc = "" +
	"\n" +
	"\x18api/users/userinfo.proto\x12\tapi.users\x1a!api/users/userinfo_messages.proto2\x92\x01\n" +
	"\vUserService\x12:\n" +
	"\vGetUserInfo\x12\x16.api.users.UserRequest\x1a\x13.api.users.UserInfo\x12G\n" +
	"\x0eUpdateUserInfo\x12 .api.users.UserInfoUpdateRequest\x1a\x13.api.users.UserInfoB\x9b\x01\n" +
	"\rcom.api.usersB\rUserinfoProtoP\x01Z6smart-analytics/assistants/grpc/protobuf/pkg/api/users\xa2\x02\x03AUX\xaa\x02\tApi.Users\xca\x02\tApi\\Users\xe2\x02\x15Api\\Users\\GPBMetadata\xea\x02\n" +
	"Api::Usersb\x06proto3"

var file_api_users_userinfo_proto_goTypes = []any{
	(*UserRequest)(nil),           // 0: api.users.UserRequest
	(*UserInfoUpdateRequest)(nil), // 1: api.users.UserInfoUpdateRequest
	(*UserInfo)(nil),              // 2: api.users.UserInfo
}
var file_api_users_userinfo_proto_depIdxs = []int32{
	0, // 0: api.users.UserService.GetUserInfo:input_type -> api.users.UserRequest
	1, // 1: api.users.UserService.UpdateUserInfo:input_type -> api.users.UserInfoUpdateRequest
	2, // 2: api.users.UserService.GetUserInfo:output_type -> api.users.UserInfo
	2, // 3: api.users.UserService.UpdateUserInfo:output_type -> api.users.UserInfo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_userinfo_proto_init() }
func file_api_users_userinfo_proto_init() {
	if File_api_users_userinfo_proto != nil {
		return
	}
	file_api_users_userinfo_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_userinfo_proto_rawDesc), len(file_api_users_userinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_userinfo_proto_goTypes,
		DependencyIndexes: file_api_users_userinfo_proto_depIdxs,
	}.Build()
	File_api_users_userinfo_proto = out.File
	file_api_users_userinfo_proto_goTypes = nil
	file_api_users_userinfo_proto_depIdxs = nil
}
