// Сервис для работы с jwt токенами

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/jwt/jwt.proto

package jwt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_jwt_jwt_proto protoreflect.FileDescriptor

const file_api_jwt_jwt_proto_rawDesc = "" +
	"\n" +
	"\x11api/jwt/jwt.proto\x12\aapi.jwt\x1a\x1aapi/jwt/jwt_messages.proto2K\n" +
	"\n" +
	"JwtService\x12=\n" +
	"\fTokenRefresh\x12\x15.api.jwt.TokenRequest\x1a\x16.api.jwt.TokenResponseB\x8a\x01\n" +
	"\vcom.api.jwtB\bJwtProtoP\x01Z4smart-analytics/assistants/grpc/protobuf/pkg/api/jwt\xa2\x02\x03AJX\xaa\x02\aApi.Jwt\xca\x02\aApi\\Jwt\xe2\x02\x13Api\\Jwt\\GPBMetadata\xea\x02\bApi::Jwtb\x06proto3"

var file_api_jwt_jwt_proto_goTypes = []any{
	(*TokenRequest)(nil),  // 0: api.jwt.TokenRequest
	(*TokenResponse)(nil), // 1: api.jwt.TokenResponse
}
var file_api_jwt_jwt_proto_depIdxs = []int32{
	0, // 0: api.jwt.JwtService.TokenRefresh:input_type -> api.jwt.TokenRequest
	1, // 1: api.jwt.JwtService.TokenRefresh:output_type -> api.jwt.TokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_jwt_jwt_proto_init() }
func file_api_jwt_jwt_proto_init() {
	if File_api_jwt_jwt_proto != nil {
		return
	}
	file_api_jwt_jwt_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_jwt_jwt_proto_rawDesc), len(file_api_jwt_jwt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_jwt_jwt_proto_goTypes,
		DependencyIndexes: file_api_jwt_jwt_proto_depIdxs,
	}.Build()
	File_api_jwt_jwt_proto = out.File
	file_api_jwt_jwt_proto_goTypes = nil
	file_api_jwt_jwt_proto_depIdxs = nil
}
