// Сервис для работы с jwt токенами

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/jwt/jwt_messages.proto

package jwt

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,json=user_id,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_api_jwt_jwt_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_jwt_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_api_jwt_jwt_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_api_jwt_jwt_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_jwt_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_api_jwt_jwt_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_api_jwt_jwt_messages_proto protoreflect.FileDescriptor

const file_api_jwt_jwt_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/jwt/jwt_messages.proto\x12\aapi.jwt\x1a\x1bbuf/validate/validate.proto\"0\n" +
	"\fTokenRequest\x12 \n" +
	"\x06userId\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\auser_id\"D\n" +
	"\rTokenResponse\x12\x1d\n" +
	"\x05token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x03R\x05token\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05validB\x92\x01\n" +
	"\vcom.api.jwtB\x10JwtMessagesProtoP\x01Z4smart-analytics/assistants/grpc/protobuf/pkg/api/jwt\xa2\x02\x03AJX\xaa\x02\aApi.Jwt\xca\x02\aApi\\Jwt\xe2\x02\x13Api\\Jwt\\GPBMetadata\xea\x02\bApi::Jwtb\x06proto3"

var (
	file_api_jwt_jwt_messages_proto_rawDescOnce sync.Once
	file_api_jwt_jwt_messages_proto_rawDescData []byte
)

func file_api_jwt_jwt_messages_proto_rawDescGZIP() []byte {
	file_api_jwt_jwt_messages_proto_rawDescOnce.Do(func() {
		file_api_jwt_jwt_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_jwt_jwt_messages_proto_rawDesc), len(file_api_jwt_jwt_messages_proto_rawDesc)))
	})
	return file_api_jwt_jwt_messages_proto_rawDescData
}

var file_api_jwt_jwt_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_jwt_jwt_messages_proto_goTypes = []any{
	(*TokenRequest)(nil),  // 0: api.jwt.TokenRequest
	(*TokenResponse)(nil), // 1: api.jwt.TokenResponse
}
var file_api_jwt_jwt_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_jwt_jwt_messages_proto_init() }
func file_api_jwt_jwt_messages_proto_init() {
	if File_api_jwt_jwt_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_jwt_jwt_messages_proto_rawDesc), len(file_api_jwt_jwt_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_jwt_jwt_messages_proto_goTypes,
		DependencyIndexes: file_api_jwt_jwt_messages_proto_depIdxs,
		MessageInfos:      file_api_jwt_jwt_messages_proto_msgTypes,
	}.Build()
	File_api_jwt_jwt_messages_proto = out.File
	file_api_jwt_jwt_messages_proto_goTypes = nil
	file_api_jwt_jwt_messages_proto_depIdxs = nil
}
